name: Publish to Siteground Hosting francescoz115.sg-host.com

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    # 👇 AGGIUNGI QUESTI STEP PER COMPILARE
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # o la versione che usi
        cache: 'npm'
        cache-dependency-path: './ficus/package-lock.json'
    
    - name: 📥 Install Dependencies
      working-directory: ./ficus 
      run: npm install
    
    - name: 🔨 Build Project
      working-directory: ./ficus 
      run: npm run build

    - name: 🐘 Install PHP Dependencies
      working-directory: ./ficus
      run: composer install --no-dev --optimize-autoloader

    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ssh.francescoz115.sg-host.com
        remote-user: u2035-q8fxzgjyzkfw
        private-ssh-key: ${{ secrets.SSH_KEY }}
        destination-path: /home/u2035-q8fxzgjyzkfw/www/francescoz115.sg-host.com/public_html/wp-content/themes/
        ssh-port: 18765
        rsync-options: --archive --verbose --compress --delete-after --exclude=node_modules --exclude=.git
